-- Create Department Table
CREATE TABLE Department (
    DEPT_ID INT PRIMARY KEY,
    DEPT_NAME VARCHAR(50)
);

-- Create Employee Table
CREATE TABLE Employee (
    EMP_ID INT PRIMARY KEY,
    SALARY INT,
    DEPT_ID INT,
    FOREIGN KEY (DEPT_ID) REFERENCES Department(DEPT_ID)
);

-- Insert Data into Department
INSERT INTO Department VALUES
(101, 'HR'),
(102, 'FINANCE'),
(103, 'MARKETING');

-- Insert Data into Employee
INSERT INTO Employee VALUES
(1, 70000, 101),
(2, 50000, 101),
(3, 60000, 101),
(4, 65000, 102),
(5, 65000, 102),
(6, 55000, 102),
(7, 60000, 103),
(8, 70000, 103),
(9, 80000, 103);

SELECT D.DEPT_NAME,E.EMP_ID,E.SALARY FROM Department D
LEFT JOIN Employee E
ON D.DEPT_ID=E.DEPT_ID AND E.SALARY=(
SELECT MAX(E1.SALARY) FROM Employee E1
WHERE E1.SALARY<(
SELECT MAX(E2.SALARY) FROM Employee E2
WHERE E2.DEPT_ID=E.DEPT_ID AND E1.DEPT_ID=E.DEPT_ID
));

SELECT D.DEPT_NAME,E.EMP_ID,E.SALARY 
FROM Department D
LEFT JOIN Employee E 
ON D.DEPT_ID=E.DEPT_ID
WHERE 1=(
SELECT COUNT(DISTINCT E1.SALARY) 
FROM Employee E1 
WHERE E1.DEPT_ID=E.DEPT_ID
AND E1.SALARY>E.SALARY
);